-- 더 이상 업그레이드할 수 없는 아이템: PARENT_ITEM_ID에 언급 X
-- 아이템 ID(ITEM_ID), 아이템 명(ITEM_NAME), 아이템의 희귀도(RARITY)를 출력
-- 결과는 아이템 ID를 기준으로 내림차순 정렬

WITH UP_LI AS (SELECT DISTINCT PARENT_ITEM_ID AS UPDATE_LIST
               FROM ITEM_TREE)

SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
LEFT JOIN UP_LI L ON I.ITEM_ID = L.UPDATE_LIST
WHERE UPDATE_LIST IS NULL
ORDER BY I.ITEM_ID DESC;