-- 코드를 입력하세요
-- 생산일자가 2022년 5월인 식품
-- 식품들의 식품 ID, 식품 이름, 총매출을 조회
-- 총매출을 기준으로 내림차순 정렬, 식품 ID를 기준으로 오름차순 정렬

WITH TOTAL AS (
SELECT PRODUCT_ID, 
       SUM(AMOUNT) AS TOT_AMOUNT
FROM FOOD_ORDER
WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31' 
GROUP BY PRODUCT_ID)

SELECT F.PRODUCT_ID, 
       PRODUCT_NAME, 
       PRICE*IFNULL(TOT_AMOUNT,0) AS TOTAL_SALES
FROM FOOD_PRODUCT F 
INNER JOIN TOTAL T ON F.PRODUCT_ID = T.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, F.PRODUCT_ID;