-- 코드를 입력하세요
-- '완료'된 중고 거래의 총금액이 70만 원 이상인 사람 (STATUS = 'DONE')
-- 회원 ID, 닉네임, 총거래금액(TOTAL_SALES)을 조회
-- 총거래금액을 기준으로 오름차순 정렬
-- WRITER_ID = USER_ID

SELECT U.USER_ID, U.NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD B 
LEFT JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
WHERE B.STATUS = 'DONE'
GROUP BY U.USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;