-- 코드를 입력하세요
-- 리뷰를 가장 많이 작성한 회원 / REVIEW_DATE의 데이트 포맷이 예시와 동일
-- 회원 이름, 리뷰 텍스트, 리뷰 작성일이 출력
-- 리뷰 작성일을 기준으로 오름차순/ 리뷰 텍스트를 기준으로 오름차순 정렬

SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW R
LEFT JOIN MEMBER_PROFILE M ON M.MEMBER_ID = R.MEMBER_ID
WHERE M.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW 
    GROUP BY MEMBER_ID
    ORDER BY COUNT(MEMBER_ID) DESC
    LIMIT 1)
ORDER BY REVIEW_DATE, REVIEW_TEXT
