-- 코드를 작성해주세요
-- 아이템의 희귀도가 'RARE'인 아이템 / PARENT_ITEM_ID가 NULL 아닌
-- 다음 업그레이드 아이템의 아이템 ID(ITEM_ID), 아이템 명(ITEM_NAME), 아이템의 희귀도(RARITY)를 출력 : 다음 업그레이드 주의
-- 아이템 ID를 기준으로 내림차순 정렬

SELECT T.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_TREE T
LEFT JOIN ITEM_INFO I ON T.ITEM_ID = I.ITEM_ID
LEFT JOIN ITEM_INFO I2 ON T.PARENT_ITEM_ID = I2.ITEM_ID
WHERE PARENT_ITEM_ID IS NOT NULL
AND I2.RARITY = 'RARE'
ORDER BY T.ITEM_ID DESC;