-- 코드를 작성해주세요
-- Python이나 C# 스킬을 가진 개발자의 정보
-- 개발자의 ID, 이메일, 이름, 성을 조회하는 SQL 문을 작성
-- ID를 기준으로 오름차순 정렬

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS 
WHERE SKILL_CODE&(SELECT CODE FROM SKILLCODES WHERE NAME ='Python') > 0
OR SKILL_CODE&(SELECT CODE FROM SKILLCODES WHERE NAME ='C#') > 0
ORDER BY ID