-- 코드를 작성해주세요
-- FISH_COUNT: BASS와 SNAPPER의 수 출력
SELECT COUNT(ID) AS FISH_COUNT
FROM FISH_INFO 
WHERE FISH_TYPE IN (
    SELECT FISH_TYPE
    FROM FISH_NAME_INFO 
    WHERE FISH_NAME = "BASS" 
    OR FISH_NAME = "SNAPPER")