-- 코드를 입력하세요
-- 각 아이스크림 성분 타입과 성분 타입에 대한 아이스크림의 총주문량(TOTAL_ORDER)
-- 주문량이 작은 순서대로 조회

SELECT I.INGREDIENT_TYPE, SUM(F.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF F
LEFT JOIN ICECREAM_INFO I ON F.FLAVOR = I.FLAVOR
GROUP BY I.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER;