-- 코드를 입력하세요
-- 게시글 제목, 게시글 ID, 댓글 ID, 댓글 작성자 ID, 댓글 내용, 댓글 작성일
SELECT GB.TITLE, GB.BOARD_ID, GR.REPLY_ID, GR.WRITER_ID, GR.CONTENTS, TO_CHAR(GR.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_BOARD GB
RIGHT JOIN USED_GOODS_REPLY GR ON GB.BOARD_ID = GR.BOARD_ID
WHERE EXTRACT(MONTH FROM GB.CREATED_DATE) = 10
ORDER BY GR.CREATED_DATE, GB.TITLE